### ISSUE TITLE
please add a LICENSE

### ISSUE THREAD

**Issue by kapouer** [vnglst/minimal-analytics#1]
No license = not free for use.
See how to do it very quickly in github:
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by vnglst** [comment]
Thanks for pointing this out, I’ll add it later today (this evening)

**Comment by vnglst** [comment]
I’ve asked the original author of the snippet for his permission for releasing this under MIT, will keep you posted here

https://twitter.com/vnglst/status/1208100207994515461?s=20
