### ISSUE TITLE
analytics v4 is a breaking change

### ISSUE THREAD

**Issue by kapouer** [vnglst/minimal-analytics#4]
i have no idea yet how to use it.

**Comment by vnglst** [comment]
Hi @kapouer what version is breaking for you? Latest version of this package is v0.1.16 
see: https://github.com/vnglst/minimal-analytics/releases/tag/v0.1.16

**Comment by vnglst** [comment]
Oh you mean v4 of the Google Analytics API!

I've not used that yet. That probably means writing a different client, the setup seems to be completely different: https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js
